---
# Based on https://github.com/glassd00r/Openwrt_Builder/tree/main
# It includes the NSS package: https://github.com/qosmio/nss-packages
name: Build OpenWRT for Xiaomi AX3600 NSS build

on:
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: qosmio/openwrt-ipq
  REMOTE_BRANCH: qualcommax-6.x-nss-wifi
  RELEASE_PREFIX: IPQ_8074_ax3600
  DEVICE_CONFIG: configs/qualcommax/ax3600
  ROLE_CONFIG: configs/common/main-router
  NSS_CONFIG: configs/common/nss

jobs:
  check_commits:
    name: Check Commits
    runs-on: ubuntu-24.04
    outputs:
      latest_commit_sha: ${{ steps.get_sha.outputs.latest_commit_sha }}
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Get the latest commit SHA
        id: get_sha
        run: echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

  build:
    name: Build OpenWRT for AX3600
    needs: [check_commits]
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget curl zstd
          sudo apt full-upgrade -y

      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "custom_repo"

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure firmware image
        run: |
          curl -SL https://raw.githubusercontent.com/danpawlik/openwrt-builder/master/configs/qualcommax/ax3600 > .config
          curl -SL https://raw.githubusercontent.com/danpawlik/openwrt-builder/master/configs/common/main-router >> .config
          curl -SL https://raw.githubusercontent.com/danpawlik/openwrt-builder/master/configs/common/nss >> .config
          sed -i '/CONFIG_ALL_KMODS=y/d' .config
          sed -i '/CONFIG_ALL_NONSHARED=y/d' .config
          make defconfig

#      - name: Remove packages that are marked as modules
#        run: |
#          grep "=m" .config | grep -v 'CONFIG_PACKAGE_libustream-mbedtls=m' | while read -r line; do module=$(echo "$line" | cut -f1 -d'='); sed -i "s/^$line$/# $module is not set/" .config; done

      - name: Download dependencies
        run: make -j $(nproc) download

      # If debugging and container is a root: export FORCE_UNSAFE_CONFIGURE=1
      - name: Build the firmware image
        run: make -j $(nproc) world

      - name: Package output
        run: tar -cvf ax_3600-images.tar bin/targets/qualcommax/ipq807x

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ax_3600-images
          path: ax_3600-images.tar

  release:
    name: Create release
    needs: [build]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ax_3600-images
      - name: Extract artifacts
        run: tar xf ax_3600-images.tar

      - name: Get current date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: bin/targets/qualcommax/ipq807x/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.RELEASE_DATE }}
          name: OpenWRT AX3600-NSS ${{ env.RELEASE_DATE }}
          body: |
            Updated prebuilt images for ${{ env.RELEASE_DATE }}
            Build Commit: ${{ needs.check_commits.outputs.latest_commit_sha }}

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
